version: "3.5"
services:
  mysql:
    image: mysql:8.0.16
    container_name: mysql
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: garaquant
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  backend:
    internal: false
